<a href="https://colab.research.google.com/github/234Kavya/Stock_Analytics/blob/main/StockDataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Collection**
The first step in doing so is to create a data set that has all the information that is potentially
useful in predicting stock returns.

In [ ]:
#for data manipulation
import numpy as np
import pandas as pd

In [ ]:
#for web scrapping
from bs4 import BeautifulSoup
import requests

In [ ]:
#for downloading Stock Data using Yahoo Finance
!pip install yfinance
import yfinance as yf

Requirement already satisfied: yfinance in /usr/local/lib/python3.10/dist-packages (0.2.40)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.0.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.25.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.31.0)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.10/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.9.4)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.2.2)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2023.4)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.10/dist-packages (from yfinance) (2.4.4)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.10/dist-packages (from yfinance) (3.17.5)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.10/dist-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.10/dist-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.3.0->yfinance) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.31->yfinance) (2024.6.2)

In [ ]:
#Scrape Nifty 50 companies from Wikipedia
url = 'https://en.wikipedia.org/wiki/NIFTY_50'
#Accessing the Wikipedia Page
response = requests.get(url)
#Parsing HTML Content
soup = BeautifulSoup(response.text , 'html.parser')
table = soup.find('table', {'id' :'constituents'})

In [ ]:
table

<table class="wikitable sortable" id="constituents">
<tbody><tr>
<th>Company name
</th>
<th>Symbol
</th>
<th>Sector<sup class="reference" id="cite_ref-14"><a href="#cite_note-14">[14]</a></sup>
</th>
<th>Date added<sup class="reference" id="cite_ref-15"><a href="#cite_note-15">[15]</a></sup>
</th></tr>
<tr>
<th><a href="/wiki/Adani_Enterprises" title="Adani Enterprises">Adani Enterprises</a>
</th>
<td>ADANIENT
</td>
<td>Diversified
</td>
<td>30 September 2022
</td></tr>
<tr>
<th><a href="/wiki/Adani_Ports_%26_SEZ" title="Adani Ports &amp; SEZ">Adani Ports &amp; SEZ</a>
</th>
<td>ADANIPORTS
</td>
<td>Infrastructure
</td>
<td>28 September 2015
</td></tr>
<tr>
<th><a href="/wiki/Apollo_Hospitals" title="Apollo Hospitals">Apollo Hospitals</a>
</th>
<td>APOLLOHOSP
</td>
<td>Healthcare
</td>
<td>31 March 2022
</td></tr>
<tr>
<th><a href="/wiki/Asian_Paints" title="Asian Paints">Asian Paints</a>
</th>
<td>ASIANPAINT
</td>
<td>Consumer Durables
</td>
<td>27 April 2012
</td></tr>
<tr>
<th><a href="/wiki/Axis_Bank" title="Axis Bank">Axis Bank</a>
</th>
<td>AXISBANK
</td>
<td>Banking
</td>
<td>27 March 2009
</td></tr>
<tr>
<th><a href="/wiki/Bajaj_Auto" title="Bajaj Auto">Bajaj Auto</a>
</th>
<td>BAJAJ-AUTO
</td>
<td>Automotive
</td>
<td>1 October 2010
</td></tr>
<tr>
<th><a href="/wiki/Bajaj_Finance" title="Bajaj Finance">Bajaj Finance</a>
</th>
<td>BAJFINANCE
</td>
<td>Financial Services
</td>
<td>29 September 2017
</td></tr>
<tr>
<th><a href="/wiki/Bajaj_Finserv" title="Bajaj Finserv">Bajaj Finserv</a>
</th>
<td>BAJAJFINSV
</td>
<td>Financial Services
</td>
<td>2 April 2018
</td></tr>
<tr>
<th><a href="/wiki/Bharat_Petroleum" title="Bharat Petroleum">Bharat Petroleum</a>
</th>
<td>BPCL
</td>
<td>Energy - Oil &amp; Gas
</td>
<td>28 October 2002
</td></tr>
<tr>
<th><a href="/wiki/Bharti_Airtel" title="Bharti Airtel">Bharti Airtel</a>
</th>
<td>BHARTIARTL
</td>
<td>Telecommunication
</td>
<td>1 March 2004
</td></tr>
<tr>
<th><a href="/wiki/Britannia_Industries" title="Britannia Industries">Britannia Industries</a>
</th>
<td>BRITANNIA
</td>
<td>Consumer Goods
</td>
<td>29 March 2019
</td></tr>
<tr>
<th><a href="/wiki/Cipla" title="Cipla">Cipla</a>
</th>
<td>CIPLA
</td>
<td>Pharmaceuticals
</td>
<td>7 October 1998
</td></tr>
<tr>
<th><a href="/wiki/Coal_India" title="Coal India">Coal India</a>
</th>
<td>COALINDIA
</td>
<td>Energy - Coal
</td>
<td>10 October 2011
</td></tr>
<tr>
<th><a href="/wiki/Divi%27s_Laboratories" title="Divi's Laboratories">Divi's Laboratories</a>
</th>
<td>DIVISLAB
</td>
<td>Pharmaceuticals
</td>
<td>25 September 2020
</td></tr>
<tr>
<th><a href="/wiki/Dr._Reddy%27s_Laboratories" title="Dr. Reddy's Laboratories">Dr. Reddy's Laboratories</a>
</th>
<td>DRREDDY
</td>
<td>Pharmaceuticals
</td>
<td>1 October 2010
</td></tr>
<tr>
<th><a href="/wiki/Eicher_Motors" title="Eicher Motors">Eicher Motors</a>
</th>
<td>EICHERMOT
</td>
<td>Automotive
</td>
<td>1 April 2016
</td></tr>
<tr>
<th><a href="/wiki/Grasim_Industries" title="Grasim Industries">Grasim Industries</a>
</th>
<td>GRASIM
</td>
<td>Materials
</td>
<td>2 April 2018
</td></tr>
<tr>
<th><a href="/wiki/HCLTech" title="HCLTech">HCLTech</a>
</th>
<td>HCLTECH
</td>
<td>Information Technology
</td>
<td>28 October 2002
</td></tr>
<tr>
<th><a href="/wiki/HDFC_Bank" title="HDFC Bank">HDFC Bank</a>
</th>
<td>HDFCBANK
</td>
<td>Banking
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/HDFC_Life" title="HDFC Life">HDFC Life</a>
</th>
<td>HDFCLIFE
</td>
<td>Financial Services
</td>
<td>31 July 2020
</td></tr>
<tr>
<th><a href="/wiki/Hero_MotoCorp" title="Hero MotoCorp">Hero MotoCorp</a>
</th>
<td>HEROMOTOCO
</td>
<td>Automotive
</td>
<td>7 October 1998
</td></tr>
<tr>
<th><a href="/wiki/Hindalco_Industries" title="Hindalco Industries">Hindalco Industries</a>
</th>
<td>HINDALCO
</td>
<td>Metals
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/Hindustan_Unilever" title="Hindustan Unilever">Hindustan Unilever</a>
</th>
<td>HINDUNILVR
</td>
<td>Consumer Goods
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/ICICI_Bank" title="ICICI Bank">ICICI Bank</a>
</th>
<td>ICICIBANK
</td>
<td>Banking
</td>
<td>25 January 2002
</td></tr>
<tr>
<th><a href="/wiki/IndusInd_Bank" title="IndusInd Bank">IndusInd Bank</a>
</th>
<td>INDUSINDBK
</td>
<td>Banking
</td>
<td>1 April 2013
</td></tr>
<tr>
<th><a href="/wiki/Infosys" title="Infosys">Infosys</a>
</th>
<td>INFY
</td>
<td>Information Technology
</td>
<td>7 October 1998
</td></tr>
<tr>
<th><a href="/wiki/ITC_Limited" title="ITC Limited">ITC</a>
</th>
<td>ITC
</td>
<td>Consumer Goods
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/JSW_Steel" title="JSW Steel">JSW Steel</a>
</th>
<td>JSWSTEEL
</td>
<td>Metals
</td>
<td>28 September 2018
</td></tr>
<tr>
<th><a href="/wiki/Kotak_Mahindra_Bank" title="Kotak Mahindra Bank">Kotak Mahindra Bank</a>
</th>
<td>KOTAKBANK
</td>
<td>Banking
</td>
<td>8 April 2010
</td></tr>
<tr>
<th><a href="/wiki/Larsen_%26_Toubro" title="Larsen &amp; Toubro">Larsen &amp; Toubro</a>
</th>
<td>LT
</td>
<td>Construction
</td>
<td>10 December 2004
</td></tr>
<tr>
<th><a href="/wiki/LTIMindtree" title="LTIMindtree">LTIMindtree</a>
</th>
<td>LTIM
</td>
<td>Information Technology
</td>
<td>13 July 2023
</td></tr>
<tr>
<th><a href="/wiki/Mahindra_%26_Mahindra" title="Mahindra &amp; Mahindra">Mahindra &amp; Mahindra</a>
</th>
<td>M&amp;M
</td>
<td>Automotive
</td>
<td>18 September 1996
</td></tr>
<tr>
<th><a href="/wiki/Maruti_Suzuki" title="Maruti Suzuki">Maruti Suzuki</a>
</th>
<td>MARUTI
</td>
<td>Automotive
</td>
<td>1 March 2004
</td></tr>
<tr>
<th><a href="/wiki/Nestl%C3%A9_India" title="Nestlé India">Nestlé India</a>
</th>
<td>NESTLEIND
</td>
<td>Consumer Goods
</td>
<td>27 September 2019
</td></tr>
<tr>
<th><a href="/wiki/NTPC_Limited" title="NTPC Limited">NTPC</a>
</th>
<td>NTPC
</td>
<td>Energy - Power
</td>
<td>24 September 2007
</td></tr>
<tr>
<th><a href="/wiki/Oil_and_Natural_Gas_Corporation" title="Oil and Natural Gas Corporation">Oil and Natural Gas Corporation</a>
</th>
<td>ONGC
</td>
<td>Energy - Oil &amp; Gas
</td>
<td>12 April 2004
</td></tr>
<tr>
<th><a class="mw-redirect" href="/wiki/PowerGrid_Corporation_of_India" title="PowerGrid Corporation of India">Power Grid</a>
</th>
<td>POWERGRID
</td>
<td>Energy - Power
</td>
<td>14 March 2008
</td></tr>
<tr>
<th><a href="/wiki/Reliance_Industries" title="Reliance Industries">Reliance Industries</a>
</th>
<td>RELIANCE
</td>
<td>Diversified
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/SBI_Life_Insurance_Company" title="SBI Life Insurance Company">SBI Life Insurance Company</a>
</th>
<td>SBILIFE
</td>
<td>Financial Services
</td>
<td>25 September 2020
</td></tr>
<tr>
<th><a class="mw-redirect" href="/wiki/Shriram_Finance" title="Shriram Finance">Shriram Finance</a>
</th>
<td>SHRIRAMFIN
</td>
<td>Financial Services
</td>
<td>28 March 2024
</td></tr>
<tr>
<th><a href="/wiki/State_Bank_of_India" title="State Bank of India">State Bank of India</a>
</th>
<td>SBIN
</td>
<td>Banking
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/Sun_Pharma" title="Sun Pharma">Sun Pharma</a>
</th>
<td>SUNPHARMA
</td>
<td>Pharmaceuticals
</td>
<td>17 January 2002
</td></tr>
<tr>
<th><a href="/wiki/Tata_Motors" title="Tata Motors">Tata Motors</a>
</th>
<td>TATAMOTORS
</td>
<td>Automotive
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/Tata_Steel" title="Tata Steel">Tata Steel</a>
</th>
<td>TATASTEEL
</td>
<td>Metals
</td>
<td>22 April 1996
</td></tr>
<tr>
<th><a href="/wiki/Tata_Consultancy_Services" title="Tata Consultancy Services">Tata Consultancy Services</a>
</th>
<td>TCS
</td>
<td>Information Technology
</td>
<td>25 February 2005
</td></tr>
<tr>
<th><a href="/wiki/Tata_Consumer_Products" title="Tata Consumer Products">Tata Consumer Products</a>
</th>
<td>TATACONSUM
</td>
<td>Consumer Goods
</td>
<td>31 March 2021
</td></tr>
<tr>
<th><a href="/wiki/Tech_Mahindra" title="Tech Mahindra">Tech Mahindra</a>
</th>
<td>TECHM
</td>
<td>Information Technology
</td>
<td>28 March 2014
</td></tr>
<tr>
<th><a href="/wiki/Titan_Company" title="Titan Company">Titan Company</a>
</th>
<td>TITAN
</td>
<td>Consumer Durables
</td>
<td>2 April 2018
</td></tr>
<tr>
<th><a href="/wiki/UltraTech_Cement" title="UltraTech Cement">UltraTech Cement</a>
</th>
<td>ULTRACEMCO
</td>
<td>Materials
</td>
<td>28 September 2012
</td></tr>
<tr>
<th><a href="/wiki/Wipro" title="Wipro">Wipro</a>
</th>
<td>WIPRO
</td>
<td>Information Technology
</td>
<td>27 September 2013
</td></tr>
</tbody></table>

In [ ]:
#Extracting Data
company_names =[]
symbol = []
sector = []
for row in table.find_all('tr')[1:]:
  head = row.find('th')
  company_name = head.text.strip()
  company_names.append(company_name)
  cols = row.find_all('td')
  sym =  cols[0].text.strip()+ '.NS'
  symbol.append(sym)
  sec = cols[1].text.strip()
  sector.append(sec)

In [ ]:
company_names

['Adani Enterprises',
 'Adani Ports & SEZ',
 'Apollo Hospitals',
 'Asian Paints',
 'Axis Bank',
 'Bajaj Auto',
 'Bajaj Finance',
 'Bajaj Finserv',
 'Bharat Petroleum',
 'Bharti Airtel',
 'Britannia Industries',
 'Cipla',
 'Coal India',
 "Divi's Laboratories",
 "Dr. Reddy's Laboratories",
 'Eicher Motors',
 'Grasim Industries',
 'HCLTech',
 'HDFC Bank',
 'HDFC Life',
 'Hero MotoCorp',
 'Hindalco Industries',
 'Hindustan Unilever',
 'ICICI Bank',
 'IndusInd Bank',
 'Infosys',
 'ITC',
 'JSW Steel',
 'Kotak Mahindra Bank',
 'Larsen & Toubro',
 'LTIMindtree',
 'Mahindra & Mahindra',
 'Maruti Suzuki',
 'Nestlé India',
 'NTPC',
 'Oil and Natural Gas Corporation',
 'Power Grid',
 'Reliance Industries',
 'SBI Life Insurance Company',
 'Shriram Finance',
 'State Bank of India',
 'Sun Pharma',
 'Tata Motors',
 'Tata Steel',
 'Tata Consultancy Services',
 'Tata Consumer Products',
 'Tech Mahindra',
 'Titan Company',
 'UltraTech Cement',
 'Wipro']

In [ ]:
sector

['Diversified',
 'Infrastructure',
 'Healthcare',
 'Consumer Durables',
 'Banking',
 'Automotive',
 'Financial Services',
 'Financial Services',
 'Energy - Oil & Gas',
 'Telecommunication',
 'Consumer Goods',
 'Pharmaceuticals',
 'Energy - Coal',
 'Pharmaceuticals',
 'Pharmaceuticals',
 'Automotive',
 'Materials',
 'Information Technology',
 'Banking',
 'Financial Services',
 'Automotive',
 'Metals',
 'Consumer Goods',
 'Banking',
 'Banking',
 'Information Technology',
 'Consumer Goods',
 'Metals',
 'Banking',
 'Construction',
 'Information Technology',
 'Automotive',
 'Automotive',
 'Consumer Goods',
 'Energy - Power',
 'Energy - Oil & Gas',
 'Energy - Power',
 'Diversified',
 'Financial Services',
 'Financial Services',
 'Banking',
 'Pharmaceuticals',
 'Automotive',
 'Metals',
 'Information Technology',
 'Consumer Goods',
 'Information Technology',
 'Consumer Durables',
 'Materials',
 'Information Technology']

In [ ]:
symbol

['ADANIENT.NS',
 'ADANIPORTS.NS',
 'APOLLOHOSP.NS',
 'ASIANPAINT.NS',
 'AXISBANK.NS',
 'BAJAJ-AUTO.NS',
 'BAJFINANCE.NS',
 'BAJAJFINSV.NS',
 'BPCL.NS',
 'BHARTIARTL.NS',
 'BRITANNIA.NS',
 'CIPLA.NS',
 'COALINDIA.NS',
 'DIVISLAB.NS',
 'DRREDDY.NS',
 'EICHERMOT.NS',
 'GRASIM.NS',
 'HCLTECH.NS',
 'HDFCBANK.NS',
 'HDFCLIFE.NS',
 'HEROMOTOCO.NS',
 'HINDALCO.NS',
 'HINDUNILVR.NS',
 'ICICIBANK.NS',
 'INDUSINDBK.NS',
 'INFY.NS',
 'ITC.NS',
 'JSWSTEEL.NS',
 'KOTAKBANK.NS',
 'LT.NS',
 'LTIM.NS',
 'M&M.NS',
 'MARUTI.NS',
 'NESTLEIND.NS',
 'NTPC.NS',
 'ONGC.NS',
 'POWERGRID.NS',
 'RELIANCE.NS',
 'SBILIFE.NS',
 'SHRIRAMFIN.NS',
 'SBIN.NS',
 'SUNPHARMA.NS',
 'TATAMOTORS.NS',
 'TATASTEEL.NS',
 'TCS.NS',
 'TATACONSUM.NS',
 'TECHM.NS',
 'TITAN.NS',
 'ULTRACEMCO.NS',
 'WIPRO.NS']

In [ ]:
#Data Retrieval
data = {}
invalid_tickers = []
for ticker in symbol:
  stock_data = yf.download(ticker , start = '2015-01-01' , end = '2023-12-31')
  if not stock_data.empty:
    stock_data['Ticker'] = ticker
    data[ticker] = stock_data
  else:
    invalid_tickers.append(ticker)

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [ ]:
data

{'ADANIENT.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01    74.399712    75.495628    73.663994    75.104774    70.692245
 2015-01-02    75.304039    76.177704    75.104774    75.472641    71.038498
 2015-01-05    75.273384    77.641479    75.212074    76.721832    72.214310
 2015-01-06    75.963120    79.381149    74.215782    76.139381    71.666061
 2015-01-07    76.637527    77.794754    73.878578    75.464973    71.031288
 ...                 ...          ...          ...          ...          ...
 2023-12-22  2815.949951  2847.600098  2791.399902  2808.350098  2808.350098
 2023-12-26  2817.000000  2893.750000  2800.100098  2865.449951  2865.449951
 2023-12-27  2880.699951  2894.800049  2833.600098  2843.350098  2843.350098
 2023-12-28  2855.000000  2867.350098  2800.100098  2809.899902  2809.899902
 2023-12-29  2823.899902  2863.300049  2802.850098  2848.949951  2848.949951

               Volume       Ticker
 Date
 2015-01-01   3946806  ADANIENT.NS
 2015-01-02   6565229  ADANIENT.NS
 2015-01-05   9404837  ADANIENT.NS
 2015-01-06  18412441  ADANIENT.NS
 2015-01-07  10863352  ADANIENT.NS
 ...              ...          ...
 2023-12-22   1513956  ADANIENT.NS
 2023-12-26   2048484  ADANIENT.NS
 2023-12-27   1698325  ADANIENT.NS
 2023-12-28   4102912  ADANIENT.NS
 2023-12-29   1507086  ADANIENT.NS

 [2221 rows x 7 columns],
 'ADANIPORTS.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   319.000000   322.500000   316.250000   319.549988   304.542114
 2015-01-02   319.350006   325.799988   318.049988   319.350006   304.351501
 2015-01-05   320.450012   327.500000   319.350006   323.799988   308.592468
 2015-01-06   321.649994   331.450012   315.600006   321.850006   306.734100
 2015-01-07   321.950012   328.700012   317.399994   321.100006   306.019318
 ...                 ...          ...          ...          ...          ...
 2023-12-22  1034.000000  1050.949951  1019.000000  1027.500000  1027.500000
 2023-12-26  1034.099976  1041.000000  1026.099976  1028.750000  1028.750000
 2023-12-27  1037.000000  1037.050049  1018.000000  1024.400024  1024.400024
 2023-12-28  1029.550049  1031.199951  1014.650024  1016.950012  1016.950012
 2023-12-29  1021.799988  1034.900024  1017.599976  1024.349976  1024.349976

              Volume         Ticker
 Date
 2015-01-01  1456204  ADANIPORTS.NS
 2015-01-02  2894058  ADANIPORTS.NS
 2015-01-05  2099786  ADANIPORTS.NS
 2015-01-06  3672197  ADANIPORTS.NS
 2015-01-07  2981544  ADANIPORTS.NS
 ...             ...            ...
 2023-12-22  5252106  ADANIPORTS.NS
 2023-12-26  2176775  ADANIPORTS.NS
 2023-12-27  2803997  ADANIPORTS.NS
 2023-12-28  4865603  ADANIPORTS.NS
 2023-12-29  2429250  ADANIPORTS.NS

 [2221 rows x 7 columns],
 'APOLLOHOSP.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01  1131.000000  1137.000000  1119.000000  1125.900024  1088.773315
 2015-01-02  1125.050049  1139.000000  1123.550049  1127.849976  1090.659058
 2015-01-05  1127.849976  1144.500000  1126.050049  1131.599976  1094.285400
 2015-01-06  1129.550049  1135.599976  1090.750000  1097.900024  1061.696655
 2015-01-07  1110.000000  1114.000000  1079.750000  1106.500000  1070.012939
 ...                 ...          ...          ...          ...          ...
 2023-12-22  5510.000000  5549.000000  5462.700195  5541.399902  5536.405762
 2023-12-26  5541.399902  5645.000000  5526.149902  5633.149902  5628.072754
 2023-12-27  5635.000000  5715.000000  5615.600098  5687.450195  5682.324219
 2023-12-28  5675.000000  5770.000000  5674.750000  5760.500000  5755.308105
 2023-12-29  5740.000000  5758.950195  5677.299805  5704.100098  5698.958984

             Volume         Ticker
 Date
 2015-01-01   76848  APOLLOHOSP.NS
 2015-01-02  172991  APOLLOHOSP.NS
 2015-01-05  137885  APOLLOHOSP.NS
 2015-01-06  164585  APOLLOHOSP.NS
 2015-01-07  208499  APOLLOHOSP.NS
 ...            ...            ...
 2023-12-22  220537  APOLLOHOSP.NS
 2023-12-26  243281  APOLLOHOSP.NS
 2023-12-27  307177  APOLLOHOSP.NS
 2023-12-28  568149  APOLLOHOSP.NS
 2023-12-29  325682  APOLLOHOSP.NS

 [2221 rows x 7 columns],
 'ASIANPAINT.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   751.099976   754.500000   747.000000   749.150024   703.691162
 2015-01-02   751.250000   781.450012   751.250000   775.049988   728.019287
 2015-01-05   779.900024   787.900024   772.700012   775.000000   727.972351
 2015-01-06   775.000000   783.000000   750.400024   756.500000   710.595032
 2015-01-07   763.400024   778.349976   759.250000   771.700012   724.872803
 ...                 ...          ...          ...          ...          ...
 2023-12-22  3309.899902  3350.800049  3287.000000  3341.300049  3341.300049
 2023-12-26  3349.949951  3391.899902  3345.199951  3383.350098  3383.350098
 2023-12-27  3381.050049  3409.949951  3354.000000  3404.449951  3404.449951
 2023-12-28  3405.000000  3419.949951  3373.050049  3397.250000  3397.250000
 2023-12-29  3410.000000  3422.949951  3383.899902  3402.399902  3402.399902

              Volume         Ticker
 Date
 2015-01-01   284935  ASIANPAINT.NS
 2015-01-02  2080850  ASIANPAINT.NS
 2015-01-05  1326999  ASIANPAINT.NS
 2015-01-06  1510720  ASIANPAINT.NS
 2015-01-07  1427667  ASIANPAINT.NS
 ...             ...            ...
 2023-12-22   930563  ASIANPAINT.NS
 2023-12-26   600190  ASIANPAINT.NS
 2023-12-27   837182  ASIANPAINT.NS
 2023-12-28   779250  ASIANPAINT.NS
 2023-12-29   615676  ASIANPAINT.NS

 [2221 rows x 7 columns],
 'AXISBANK.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   502.649994   504.000000   499.049988   503.049988   487.755188
 2015-01-02   503.200012   516.900024   501.700012   514.299988   498.663147
 2015-01-05   516.900024   520.400024   515.099976   517.549988   501.814331
 2015-01-06   513.549988   513.549988   496.750000   499.049988   483.876770
 2015-01-07   498.799988   505.350006   494.500000   498.649994   483.488953
 ...                 ...          ...          ...          ...          ...
 2023-12-22  1095.400024  1106.300049  1085.800049  1088.300049  1088.300049
 2023-12-26  1091.199951  1100.650024  1086.699951  1094.250000  1094.250000
 2023-12-27  1096.050049  1110.550049  1089.650024  1106.349976  1106.349976
 2023-12-28  1107.250000  1113.000000  1098.000000  1107.849976  1107.849976
 2023-12-29  1101.449951  1106.849976  1093.949951  1102.300049  1102.300049

               Volume       Ticker
 Date
 2015-01-01   1351985  AXISBANK.NS
 2015-01-02   3852825  AXISBANK.NS
 2015-01-05   2561430  AXISBANK.NS
 2015-01-06   5284530  AXISBANK.NS
 2015-01-07   4245189  AXISBANK.NS
 ...              ...          ...
 2023-12-22  10600025  AXISBANK.NS
 2023-12-26   5687517  AXISBANK.NS
 2023-12-27   6132936  AXISBANK.NS
 2023-12-28  14097667  AXISBANK.NS
 2023-12-29   8786731  AXISBANK.NS

 [2221 rows x 7 columns],
 'BAJAJ-AUTO.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01  2431.000000  2458.300049  2428.449951  2452.149902  1907.505737
 2015-01-02  2457.000000  2476.399902  2432.000000  2451.750000  1907.194702
 2015-01-05  2452.000000  2481.199951  2450.000000  2460.699951  1914.156860
 2015-01-06  2454.300049  2469.899902  2430.000000  2441.500000  1899.221558
 2015-01-07  2442.000000  2475.600098  2432.050049  2447.199951  1903.655396
 ...                 ...          ...          ...          ...          ...
 2023-12-22  6288.000000  6395.000000  6264.250000  6372.100098  6372.100098
 2023-12-26  6379.850098  6475.000000  6370.049805  6464.549805  6464.549805
 2023-12-27  6470.000000  6740.250000  6465.200195  6709.649902  6709.649902
 2023-12-28  6709.649902  6738.649902  6666.000000  6703.299805  6703.299805
 2023-12-29  6729.950195  6833.950195  6666.000000  6797.250000  6797.250000

              Volume         Ticker
 Date
 2015-01-01    72928  BAJAJ-AUTO.NS
 2015-01-02   164726  BAJAJ-AUTO.NS
 2015-01-05   118873  BAJAJ-AUTO.NS
 2015-01-06   580496  BAJAJ-AUTO.NS
 2015-01-07   189191  BAJAJ-AUTO.NS
 ...             ...            ...
 2023-12-22   237213  BAJAJ-AUTO.NS
 2023-12-26   302139  BAJAJ-AUTO.NS
 2023-12-27  1017894  BAJAJ-AUTO.NS
 2023-12-28   406228  BAJAJ-AUTO.NS
 2023-12-29   345626  BAJAJ-AUTO.NS

 [2221 rows x 7 columns],
 'BAJFINANCE.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   348.394989   352.000000   346.500000   349.970001   341.369476
 2015-01-02   349.000000   352.000000   341.619995   344.375000   335.911987
 2015-01-05   346.500000   352.000000   341.100006   343.475006   335.034119
 2015-01-06   345.000000   348.500000   339.220001   342.584991   334.166016
 2015-01-07   340.375000   351.795013   340.375000   349.559998   340.969574
 ...                 ...          ...          ...          ...          ...
 2023-12-22  7418.950195  7440.000000  7243.000000  7295.299805  7295.299805
 2023-12-26  7325.000000  7344.000000  7145.250000  7162.299805  7162.299805
 2023-12-27  7219.899902  7323.399902  7190.899902  7232.799805  7232.799805
 2023-12-28  7275.000000  7290.000000  7200.000000  7258.649902  7258.649902
 2023-12-29  7231.649902  7343.000000  7205.149902  7327.750000  7327.750000

              Volume         Ticker
 Date
 2015-01-01    75660  BAJFINANCE.NS
 2015-01-02   140430  BAJFINANCE.NS
 2015-01-05   144620  BAJFINANCE.NS
 2015-01-06   137810  BAJFINANCE.NS
 2015-01-07   109470  BAJFINANCE.NS
 ...             ...            ...
 2023-12-22  1129485  BAJFINANCE.NS
 2023-12-26  1225844  BAJFINANCE.NS
 2023-12-27  1605279  BAJFINANCE.NS
 2023-12-28  1856064  BAJFINANCE.NS
 2023-12-29   912802  BAJFINANCE.NS

 [2221 rows x 7 columns],
 'BAJAJFINSV.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   130.990005   132.229996   128.000000   128.660004   128.046722
 2015-01-02   129.169998   129.800003   126.699997   127.565002   126.956955
 2015-01-05   126.805000   128.399994   125.260002   125.870003   125.270027
 2015-01-06   125.000000   125.315002   121.559998   122.959999   122.373894
 2015-01-07   123.025002   124.084999   120.820000   122.855003   122.269409
 ...                 ...          ...          ...          ...          ...
 2023-12-22  1669.000000  1690.000000  1663.599976  1672.050049  1672.050049
 2023-12-26  1675.000000  1684.000000  1637.050049  1645.300049  1645.300049
 2023-12-27  1657.000000  1674.050049  1653.800049  1669.449951  1669.449951
 2023-12-28  1674.050049  1698.800049  1667.199951  1681.199951  1681.199951
 2023-12-29  1682.449951  1692.699951  1674.599976  1685.800049  1685.800049

              Volume         Ticker
 Date
 2015-01-01   293920  BAJAJFINSV.NS
 2015-01-02   435600  BAJAJFINSV.NS
 2015-01-05   315660  BAJAJFINSV.NS
 2015-01-06   377240  BAJAJFINSV.NS
 2015-01-07   731140  BAJAJFINSV.NS
 ...             ...            ...
 2023-12-22  1279614  BAJAJFINSV.NS
 2023-12-26  1296291  BAJAJFINSV.NS
 2023-12-27  1181177  BAJAJFINSV.NS
 2023-12-28  1360425  BAJAJFINSV.NS
 2023-12-29   738203  BAJAJFINSV.NS

 [2221 rows x 7 columns],
 'BPCL.NS':                   Open        High         Low       Close   Adj Close  \
 Date
 2015-01-01  216.300003  219.166672  214.066666  218.066666  133.195053
 2015-01-02  216.966660  218.633331  214.149994  214.800003  131.199783
 2015-01-05  215.000000  216.483337  213.766663  215.216660  131.454285
 2015-01-06  217.466660  218.433334  210.000000  213.050003  130.130890
 2015-01-07  212.333328  216.449997  212.333328  214.983337  131.311737
 ...                ...         ...         ...         ...         ...
 2023-12-22  449.700012  453.350006  445.049988  446.649994  446.649994
 2023-12-26  448.000000  456.500000  444.500000  451.600006  451.600006
 2023-12-27  453.950012  456.399994  448.299988  454.700012  454.700012
 2023-12-28  456.000000  470.850006  454.750000  465.799988  465.799988
 2023-12-29  454.500000  458.000000  448.649994  450.649994  450.649994

               Volume   Ticker
 Date
 2015-01-01   1446501  BPCL.NS
 2015-01-02   3071145  BPCL.NS
 2015-01-05   3283116  BPCL.NS
 2015-01-06   6560505  BPCL.NS
 2015-01-07   3928182  BPCL.NS
 ...              ...      ...
 2023-12-22   5779632  BPCL.NS
 2023-12-26  11488225  BPCL.NS
 2023-12-27   6199044  BPCL.NS
 2023-12-28  22591668  BPCL.NS
 2023-12-29   8544220  BPCL.NS

 [2221 rows x 7 columns],
 'BHARTIARTL.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   319.405579   328.868774   316.927124   327.066254   312.380219
 2015-01-02   327.877380   330.761414   326.255127   329.003967   314.230957
 2015-01-05   330.085480   330.085480   320.487091   321.703766   307.258514
 2015-01-06   320.937714   320.937714   313.998016   319.180267   304.848297
 2015-01-07   317.197479   322.650116   315.890686   319.946320   305.579956
 ...                 ...          ...          ...          ...          ...
 2023-12-22   981.900024   998.950012   975.549988   989.549988   989.549988
 2023-12-26   995.000000  1002.500000   989.650024   999.849976   999.849976
 2023-12-27  1000.000000  1024.050049   998.000000  1021.200012  1021.200012
 2023-12-28  1023.900024  1041.949951  1022.200012  1036.699951  1036.699951
 2023-12-29  1033.150024  1043.250000  1024.400024  1032.199951  1032.199951

              Volume         Ticker
 Date
 2015-01-01  2460188  BHARTIARTL.NS
 2015-01-02  2795887  BHARTIARTL.NS
 2015-01-05  1605267  BHARTIARTL.NS
 2015-01-06  3916948  BHARTIARTL.NS
 2015-01-07  4899318  BHARTIARTL.NS
 ...             ...            ...
 2023-12-22  4605120  BHARTIARTL.NS
 2023-12-26  2460643  BHARTIARTL.NS
 2023-12-27  4791379  BHARTIARTL.NS
 2023-12-28  5288328  BHARTIARTL.NS
 2023-12-29  4631749  BHARTIARTL.NS

 [2221 rows x 7 columns],
 'BRITANNIA.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   919.275024   931.500000   911.625000   915.750000   816.541199
 2015-01-02   921.000000   942.500000   919.000000   939.275024   837.517578
 2015-01-05   944.500000   963.474976   936.150024   939.924988   838.097229
 2015-01-06   942.500000   955.000000   925.000000   940.950012   839.010986
 2015-01-07   945.974976  1004.450012   945.974976   997.875000   889.769165
 ...                 ...          ...          ...          ...          ...
 2023-12-22  5075.000000  5183.700195  5050.049805  5161.100098  5161.100098
 2023-12-26  5155.000000  5244.500000  5146.000000  5235.950195  5235.950195
 2023-12-27  5242.000000  5245.000000  5160.000000  5216.799805  5216.799805
 2023-12-28  5224.950195  5338.649902  5186.750000  5282.000000  5282.000000
 2023-12-29  5260.549805  5386.049805  5238.649902  5338.450195  5338.450195

             Volume        Ticker
 Date
 2015-01-01   96950  BRITANNIA.NS
 2015-01-02  308986  BRITANNIA.NS
 2015-01-05  344472  BRITANNIA.NS
 2015-01-06  228284  BRITANNIA.NS
 2015-01-07  947474  BRITANNIA.NS
 ...            ...           ...
 2023-12-22  582688  BRITANNIA.NS
 2023-12-26  574310  BRITANNIA.NS
 2023-12-27  241944  BRITANNIA.NS
 2023-12-28  655367  BRITANNIA.NS
 2023-12-29  535691  BRITANNIA.NS

 [2221 rows x 7 columns],
 'CIPLA.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   626.500000   634.799988   626.500000   628.400024   602.885681
 2015-01-02   633.000000   637.549988   629.349976   630.150024   604.564697
 2015-01-05   626.000000   638.000000   626.000000   633.000000   607.298889
 2015-01-06   631.000000   632.000000   610.500000   614.349976   589.406128
 2015-01-07   614.349976   617.799988   604.500000   611.950012   587.103638
 ...                 ...          ...          ...          ...          ...
 2023-12-22  1230.050049  1242.500000  1221.650024  1235.599976  1235.599976
 2023-12-26  1240.000000  1250.000000  1231.849976  1244.949951  1244.949951
 2023-12-27  1247.000000  1250.349976  1236.699951  1239.750000  1239.750000
 2023-12-28  1239.750000  1263.800049  1239.750000  1260.800049  1260.800049
 2023-12-29  1264.000000  1267.599976  1242.050049  1246.300049  1246.300049

              Volume    Ticker
 Date
 2015-01-01   596787  CIPLA.NS
 2015-01-02   688999  CIPLA.NS
 2015-01-05  1282895  CIPLA.NS
 2015-01-06  1615490  CIPLA.NS
 2015-01-07   813936  CIPLA.NS
 ...             ...       ...
 2023-12-22  1969524  CIPLA.NS
 2023-12-26   820163  CIPLA.NS
 2023-12-27  2528609  CIPLA.NS
 2023-12-28  2592699  CIPLA.NS
 2023-12-29  1794218  CIPLA.NS

 [2221 rows x 7 columns],
 'COALINDIA.NS':                   Open        High         Low       Close   Adj Close  \
 Date
 2015-01-01  383.000000  383.450012  378.549988  380.049988  173.494568
 2015-01-02  380.500000  386.600006  379.950012  381.750000  174.270599
 2015-01-05  381.000000  386.000000  377.000000  380.250000  173.585846
 2015-01-06  374.000000  382.100006  373.700012  379.950012  173.448944
 2015-01-07  380.000000  384.450012  372.549988  374.700012  171.052246
 ...                ...         ...         ...         ...         ...
 2023-12-22  359.000000  367.399994  356.399994  363.250000  359.113190
 2023-12-26  363.799988  371.799988  362.500000  366.049988  361.881287
 2023-12-27  367.000000  369.200012  362.399994  365.600006  361.436432
 2023-12-28  366.799988  382.500000  365.799988  380.950012  376.611633
 2023-12-29  381.500000  381.700012  374.250000  376.000000  371.717987

               Volume        Ticker
 Date
 2015-01-01    540225  COALINDIA.NS
 2015-01-02    969551  COALINDIA.NS
 2015-01-05   1857013  COALINDIA.NS
 2015-01-06   4644316  COALINDIA.NS
 2015-01-07   2628276  COALINDIA.NS
 ...              ...           ...
 2023-12-22  13916380  COALINDIA.NS
 2023-12-26  11910267  COALINDIA.NS
 2023-12-27   7890042  COALINDIA.NS
 2023-12-28  28310022  COALINDIA.NS
 2023-12-29   8859317  COALINDIA.NS

 [2221 rows x 7 columns],
 'DIVISLAB.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01   867.400024   876.500000   862.250000   872.724976   807.733948
 2015-01-02   877.000000   884.750000   873.000000   876.450012   811.181519
 2015-01-05   876.375000   882.825012   866.250000   871.174988   806.299255
 2015-01-06   865.000000   865.000000   833.500000   837.075012   774.738831
 2015-01-07   838.099976   849.575012   817.500000   824.825012   763.400940
 ...                 ...          ...          ...          ...          ...
 2023-12-22  3650.000000  3762.899902  3643.949951  3694.949951  3694.949951
 2023-12-26  3699.050049  3897.000000  3694.000000  3863.500000  3863.500000
 2023-12-27  3894.000000  3917.000000  3845.500000  3884.250000  3884.250000
 2023-12-28  3900.000000  3952.000000  3861.350098  3939.949951  3939.949951
 2023-12-29  3949.000000  3949.000000  3896.350098  3903.899902  3903.899902

              Volume       Ticker
 Date
 2015-01-01   186924  DIVISLAB.NS
 2015-01-02   204160  DIVISLAB.NS
 2015-01-05   121542  DIVISLAB.NS
 2015-01-06   682896  DIVISLAB.NS
 2015-01-07   415972  DIVISLAB.NS
 ...             ...          ...
 2023-12-22   898967  DIVISLAB.NS
 2023-12-26  1249185  DIVISLAB.NS
 2023-12-27   598775  DIVISLAB.NS
 2023-12-28   668311  DIVISLAB.NS
 2023-12-29   262845  DIVISLAB.NS

 [2221 rows x 7 columns],
 'DRREDDY.NS':                    Open         High          Low        Close    Adj Close  \
 Date
 2015-01-01  3230.000000  3235.000000  3204.000000  3210.500000  3022.588135
 2015-01-02  3220.000000  3242.649902  3215.000000  3221.399902  3032.850342
 2015-01-05  3221.399902  3221.399902  3141.000000  3148.399902  2964.123047
 2015-01-06  3130.000000  3130.000000  3055.000000  3065.550049  2886.122070
 2015-01-07  3075.100098  3078.050049  3010.000000  3039.199951  2861.314209

In [ ]:
invalid_tickers

[]

if we have invalid_tickers then we have to handle them
```
# Filter out invalid tickers from the original lists
valid_symbol = [ticker for ticker in symbol if ticker not in invalid_tickers]
valid_company_names = [company_names[i] for i in range(len(company_names)) if symbol[i] not in invalid_tickers]
```

In [ ]:
#Merging data from all tickers into a single DataFrame.
if data:
    all_data = pd.concat(data.values())
else:
    all_data = pd.DataFrame()

In [ ]:
all_data

,Open,High,Low,Close,Adj Close,Volume,Ticker
Date,,,,,,,
2015-01-01,74.399712,75.495628,73.663994,75.104774,70.692245,3946806,ADANIENT.NS
2015-01-02,75.304039,76.177704,75.104774,75.472641,71.038498,6565229,ADANIENT.NS
2015-01-05,75.273384,77.641479,75.212074,76.721832,72.214310,9404837,ADANIENT.NS
2015-01-06,75.963120,79.381149,74.215782,76.139381,71.666061,18412441,ADANIENT.NS
2015-01-07,76.637527,77.794754,73.878578,75.464973,71.031288,10863352,ADANIENT.NS
...,...,...,...,...,...,...,...
2023-12-22,435.299988,466.299988,434.000000,462.649994,461.665405,23040407,WIPRO.NS
2023-12-26,454.000000,475.799988,448.350006,470.100006,469.099579,27314322,WIPRO.NS
2023-12-27,468.500000,475.399994,464.100006,470.950012,469.947784,12631496,WIPRO.NS
2023-12-28,472.549988,477.399994,467.649994,469.450012,468.450958,8419978,WIPRO.NS
2023-12-29,470.950012,475.350006,466.100006,471.299988,470.296997,7980570,WIPRO.NS

In [ ]:
# Create a DataFrame
if not all_data.empty:
  all_data = all_data.reset_index()
  all_data['Date'] = pd.to_datetime(all_data['Date'])

In [ ]:
all_data = all_data[(all_data['Date'].dt.year >= 2015) & (all_data['Date'].dt.year <= 2023)]
all_data.to_csv('nifty_50_stock_prices_2015_2023.csv', index=False)